name: firstworkflow(manual)
on: 
    workflow_dispatch:
    push:
    # due condizioni in and
      branches:
        - development
      #paths:
       # - '**.js'      
env:
    FILE_PATH: log.txt
    FILE_NAME: log_file
jobs:
    print_hello:
      runs-on: ubuntu-latest
      steps:
        - name: print_hello_on_terminal_windows
          run: echo 'Hello form first job 2'
    print_github_object:
      runs-on: ubuntu-latest
      steps:
        - name: print obj
          run: echo '${{toJson(github.retention_days)}}'
    set-output:
      needs: [print_hello, print_github_object]
      runs-on: ubuntu-latest
      continue-on-error: true
      steps:
        - name: create_variable
          id: varCreate
          run: |
              stringa="sono una stringa a caso"
              echo "content=$stringa">>$GITHUB_OUTPUT
        - name: read_output
          run: echo '${{steps.varCreate.outputs.content}}'
        - name: savetofile
          run: |
              echo "${{steps.varCreate.outputs.content}}" > log.txt
              cat log.txt
    set-output2:
      timeout-minutes: 1
      runs-on: windows-latest
      steps:
        - name: create_variable
          id: varCreate
          run: |
              $stringa="sono una stringa a caso"
              "content=$stringa" | Out-file -FilePath $env:GITHUB_OUTPUT -Append
        - name: read_output
          run: echo '${{steps.varCreate.outputs.content}}'
        - name: savetofile
          run: |
              echo "${{steps.varCreate.outputs.content}}" > log.txt
              cat log.txt
        - name: upload_artifact
          uses: actions/upload-artifact@v4
          with:
              # path: log.txt
              path: ${{env.FILE_PATH}}
              # name: log_file
              name: ${{env.FILE_NAME}}
        - name: download_artifact
          uses: actions/upload-artifact@v4
          with:
              path: log.txt
        - name: Display structure of downloaded files
          run: |
               ls -R
               cat log.txt



