name: firstworkflow(manual)
on: push
jobs:
    print_hello:
      runs-on: ubuntu-latest
      steps:
        - name: print_hello_on_terminal_windows
          run: echo 'Hello form first job 2'
    print_github_object:
      runs-on: ubuntu-latest
      steps:
        - name: print obj
          run: echo '${{toJson(github.retention_days)}}'
    set-output:
      runs-on: ubuntu-latest
      steps:
        - name: create_variable
          id: varCreate
          run: |
              stringa="sono una stringa a caso"
              echo "content=$stringa">>$GITHUB_OUTPUT
        - name: read_output
          run: echo '${{steps.varCreate.outputs.content}}'
    set-output2:
      runs-on: windows-latest
      steps:
        - name: create_variable
          id: varCreate
          run: |
              set "stringa=sono una stringa a caso"
              echo "content=$stringa">>$GITHUB_OUTPUT
        - name: read_output
          run: echo '${{steps.varCreate.outputs.content}}'
